app.constant("constantApi",{
	"product":"product",
	"addImagesOfProduct":"addImagesOfProduct",
	"address":"address",
	"clientFeedback":"clientFeedback",
	"removeIndiImage":"removeIndiImage/",
	"contactUs":"contactUs",
	"newsLater":"newsLater",
	"cms":"cms",
});