app.constant("constantApi",{
	adminLoginApi: 'web/users/login',
	country: 'web/country',
	state:'web/state',
	city:'web/city',
	petSize:"web/pet-size",
	petType:"web/pet-type",
	language:"web/language",
	bubHubPost:"web/bub-hub-post",
	petBreed:"web/pet-breed",
	loveBubHubPost:"web/love-post",
	reportAbuseReason:"web/report-abuse-default",
	locationImport:"web/import-location",
	countryFlagSignedUrl:"web/country/get-country-flag-upload-sign-url",
        news:"web/pet-news/get-all-news",
        deleteNews:"web/pet-news",
	bubHubPostLike : "web/bub-hub-like-list",
	bubHubPostComment:"web/bub-hub-comment-list",
	bubHubReportList:"web/bub-hub-abuse-list",
        getUser:"web/users/list",
        deleteUser:"web/users",
        userData:"web/users/user-details",
        BubTalkCat:"web/bubtalk-category",
        bubTalkCatImage:"web/country/get-bub-talk-category-flag-upload-sign-url",
        newsImageSignedUrl:"web/pet-news/get-news-upload-sign-url",
        addPetNews:"web/pet-news",
        bubTalkThread:"web/bubtalk-thread/listing",
	bubTalkTopic:"web/bubtalk-topic"
});