app.constant("constant",{
    "serverUrl":"http://localhost:7500/",
    "serverImagePath":"demoNode/content/",
    "product":"product",
    "cms":"cms/",
    "contactUs":"contactUs",
    "getAddress":"address",
    "goal":"goal",
    "clientFeedback":"clientFeedback",
})